SDK-382: update 2.3 C++ samples to support drowsiness
Affectiva/cpp-sdk-samples pull request #112
Opened 2020-10-07 23:41 UTC by wiperz1789

Added support for Drowsiness, can be enabled using --drowsiness. Can write drowsiness data to CSV file and overlaid output video.

Adding everyone to review.

2020-10-08 14:24 UTC, adennie commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +            "Draw drowsiness metrics on screen.");
for consistency with other options, this message should be "Enable drowsiness detection".  I'm curious why this option is configured differently than "object", "occupant", and "body" -- shouldn't they be analogous to one another?  Should those other ones be configured like this one?

2020-10-08 14:24 UTC, adennie commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +                                         !program_options.disable_logging, program_options.draw_id, program_options.show_drowsiness);
maybe we should just pass program_options to the PlottingImageListener constructor...

2020-10-08 14:24 UTC, adennie commented on vision/frame-detector-webcam-demo/WebcamDemo.cpp
> +        ("drowsiness", po::value<bool>(&program_options.show_drowsiness)->default_value(false), "Draw "
same comment as above in VideoDemo.cpp

2020-10-08 15:00 UTC, wiperz1789 commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +                                         !program_options.disable_logging, program_options.draw_id, program_options.show_drowsiness);
@adennie I tried that but the problem here is we have two ProgramOptions one for video and other for webcam, and PlottingImageListener takes input from both of them. To solve that problem I was planning to create a new class ProgramOptions(which I already have locally) with two struct inside it but then it would have complicated this story. Let me know your thoughts, should I go ahead with new class?

2020-10-08 16:21 UTC, adennie commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +                                         !program_options.disable_logging, program_options.draw_id, program_options.show_drowsiness);
Ah, I see.  OK, I don't really want to delay this story, so let's break that out into a separate refactoring story.

2020-10-08 16:24 UTC, lindsay-richter commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +                                         !program_options.disable_logging, program_options.draw_id, program_options.show_drowsiness);
@wiperz1789 would it work to have 2 different constructors instead, one that takes WebcamDemo::ProgramOptions and another that takes VideoDemo::ProgramOptions?

2020-10-08 16:27 UTC, lindsay-richter commented on vision/shared/Visualizer.cpp
> +        auto drowsiness_metric = face.getDrowsinessMetric();
can this variable be const?

2020-10-08 16:30 UTC, wiperz1789 commented on vision/shared/Visualizer.cpp
> +        auto drowsiness_metric = face.getDrowsinessMetric();
i think so, will fix if possible!

2020-10-08 16:32 UTC, wiperz1789 commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +                                         !program_options.disable_logging, program_options.draw_id, program_options.show_drowsiness);
I think we can do that, will try it

2020-10-08 16:36 UTC, wiperz1789 commented on vision/frame-detector-video-demo/VideoDemo.cpp
> +            "Draw drowsiness metrics on screen.");
@adennie I can try that but then do you want to add extra check if we enable `occupants or body with drowsiness` or just ignore `drowsiness` if `faces` is not enabled?

2020-10-08 23:06 UTC, umangmehta12 requested changes

2020-10-08 23:23 UTC, wiperz1789 commented on vision/shared/Visualizer.cpp
> +    const auto emotions = face.getEmotions();
@umangmehta12 we can't because there are being updated in the next line

2020-10-08 23:24 UTC, wiperz1789 commented on vision/shared/ProgramOptions.h
> +    enum DetectionType {
I can undo these changes if you want? but the next refactoring story would be bigger this will pave a way towards next story.

2020-10-08 23:26 UTC, wiperz1789 commented on vision/shared/Visualizer.cpp
> +    const auto emotions = face.getEmotions();
ahh... I thought  they were overwritten in the next line... will change that

2020-10-08 23:28 UTC, umangmehta12 commented on vision/shared/Visualizer.cpp
> +    const auto emotions = face.getEmotions();
I don't see so, we are accessing them but not updating them.

2020-10-08 23:30 UTC, umangmehta12 commented on vision/shared/Visualizer.cpp
> +    const auto emotions = face.getEmotions();
oh I see the int to string conversation might not be allowed

2020-10-08 23:31 UTC, umangmehta12 commented on vision/shared/ProgramOptions.h
> +    enum DetectionType {
maybe update to have a base struct for now and derive from it and in the next refactoring we could do the rest

2020-10-08 23:36 UTC, wiperz1789 commented on vision/shared/ProgramOptions.h
> +    enum DetectionType {
@umangmehta12 that will add additional scope for more testing as we'll be changing the design on how things are accessed. I think in the next story we can do the above mentioned changes?

2020-10-09 14:10 UTC, adennie commented
General comment about refactoring the program options logic ... I think there are a set of options that are common to webcam and video modes, and PlottingImageListener only cares about these common options.  We could implement those common options in a base class with the video and webcam options being subclasses, or maybe even simpler would be to break out the video and webcam options into two additional, unrelated structs used only within the video and webcam apps.  But let's do that in a separate PR.

2020-10-09 14:11 UTC, adennie approved these changes

2020-10-09 14:39 UTC, merged