Change the opacity of face bbox and points to 70%
Affectiva/cpp-sdk-samples pull request #120
Opened 2020-12-17 14:59 UTC by ahmedalmoraly

2020-12-17 22:57 UTC, umangmehta12 requested changes

2020-12-17 22:57 UTC, umangmehta12 commented on vision/shared/Visualizer.cpp
> +    cv::Mat overlay = img.clone();
@ahmedalmoraly do we really need to do a deep copy here or a shallow copy would suffice?

2020-12-17 22:57 UTC, umangmehta12 commented on vision/shared/Visualizer.cpp
> +        cv::Mat roi_overlay = roi_original.clone();
similarly as above

2020-12-22 22:27 UTC, wiperz1789 commented
LGTM apart from the comments.

2020-12-30 16:56 UTC, adennie approved these changes
Looks good, minor comment about not needing to clone underlying images for overlay Mats.

2020-12-30 16:56 UTC, adennie commented on vision/shared/Visualizer.cpp
> +    cv::Mat overlay = img.clone();
actually do we need either kind of copy?  Doesn't the overlay just need to be a blank image onto which we'll draw the face points?

2021-01-05 15:09 UTC, ahmedalmoraly commented on vision/shared/Visualizer.cpp
> +    cv::Mat overlay = img.clone();
yes. opencv doesn't have a way to change opacity of an image. They way it's done is by blending two images each with a different opacity. 

So in here (and the same applies to `drowBoundingBox`), we want to blend two images; the source (background) and the overlay (the part of the image with the circles). And since `cv::circle` updates the image directly, we need to create a deep copy of the image, and use it to draw the circles, so it doesn't affect the original image. 
Then we blend the original and the overlay using `cv::addWeighted`

2021-01-06 16:18 UTC, umangmehta12 commented on vision/shared/Visualizer.cpp
> +    cv::Mat overlay = img.clone();
Understood, did you see any performance impact to the FPS after the change?

2021-01-06 16:19 UTC, umangmehta12 approved these changes
Looks good to me!

2021-01-07 21:20 UTC, wiperz1789 approved these changes
LGTM

2021-01-11 14:50 UTC, merged