SDK-4228 and SDK-3915
Affectiva/cpp-sdk-samples pull request #122
Opened 2021-02-04 12:05 UTC by wiperz1789

Contains support for emotion-sdk and also supports blink, blink-rate and neutral

2021-03-03 18:45 UTC, adennie requested changes

2021-03-03 18:45 UTC, adennie commented on CMakeLists.txt
> +if (MSVC)
* don't need to specify `Boost_DEBUG OFF`, that's off by default.
* `Boost_COMPILER` is specified twice below

2021-03-03 19:38 UTC, wiperz1789 commented on CMakeLists.txt
> +if (MSVC)
@adennie  I added `Boost_DEBUG ON` to test boost library issue. turned off later, will remove it.

2021-03-08 14:10 UTC, adennie approved these changes
Looks good, just wanted to remove some commented out logic.  OK to to merge after that.

2021-03-08 14:10 UTC, adennie commented on CMakeLists.txt
> +
I don't think we need this commented out logic below.  Let's remove it so it doesn't get merged in.

2021-03-08 14:20 UTC, umangmehta12 approved these changes
LGTM apart from Andy's comment

2021-03-08 14:30 UTC, wiperz1789 commented on CMakeLists.txt
> +
fixed

2021-03-08 14:33 UTC, merged